services:
  - type: web
    name: tic-tac-mini-game
    buildCommand: npm install && npm run generate && npm run build
    startCommand: npm run start:prod
    autoDeploy: true
    region: oregon
    healthCheckPath: /health
    runtime: node
